### ISSUE TITLE
Minimum supported JIRA and Confluence versions

### ISSUE THREAD

**Issue by brandonhinds** [pru-mike/rocketchat-jira-webhook#2]
Are there minimum supported versions of JIRA and Confluence for this integration? I have setup the Docker container, and when I enable DEBUG logging on the container I can see the messages from Rocket are being received, and JIRA tickets and Confluence IDs are being identified, but nothing is getting posted in the Rocket channels.

We are running older versions of JIRA and Confluence (v8.5.5 and 7.10.2 respectively), and our Rocket.Chat is v4.4.0. I am wondering if there were breaking changes between the API responses of those versions and whichever versions this integration was designed to work against.

Alternatively is there any other way I can debug why the messages are not being posted into Rocket.Chat (e.g. capturing the responses from the Docker container)? Unfortunately I don't know anything about GO so I can't understand what is happening in the source code.

**Comment by pru-mike** [comment]
>Are there minimum supported versions of JIRA and Confluence for this integration?

I don't sure. Where is docs [1](https://docs.atlassian.com/DAC/rest/jira/6.1.html), [2](https://developer.atlassian.com/server/jira/platform/jira-rest-api-version-2-tutorial-8946379/) but i can't find since what version JIRA REST API v2 was started. 
I think API is pretty old and should work fine with your JIRA version. You can check this by hand, try to request something like https://your.jira.server/rest/api/2/issue/TEST-123 by cURL with basic auth or just through browser


>Alternatively is there any other way I can debug why the messages are not being posted into Rocket.Chat (e.g. capturing the responses from the Docker container)?

When you enable DEBUG in application (log_level = "debug" in config, see [everything.toml](https://github.com/pru-mike/rocketchat-jira-webhook/blob/master/examples/everything.toml)) and post valid jira key in chat, you should see something like
```
2022/05/24 18:42:22 DEBUG input message: {Token:2sj2137d74f ChannelID:GENERAL ChannelName:general UserID:qHMxfioRZBNhtZ3oz UserName:Test Text:TEST-1234 MessageID:vqnesPZaNpJk5vH42 SiteURL:http://localhost:3000 Timestamp:2022-05-24 18:42:21.844 +0000 UTC IsEdited:false Bot:false Alias: TriggerWord:}
2022/05/24 18:42:22 DEBUG found jira keys '[TEST-1234]'
```
So if you see 'found jira keys' and don't see any error it's pretty sure that integration works just fine. So you need to examine you Rocket.Chat logs, and you need to be sure about Rocket.Chat integration configuration.
For me it works with following settings:
- Outgoing WebHook Integration
- Enabled ON
- Channel (all_publin_channels)
- URL (something like http://my.corp.com:4567/jira)
- Post as (valid user with proper rights)

As well, you can try to test integration with Rocket.Chat local installation, [this](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/4.6.1/docker-compose.yml) works for me. With local installation it's easy to examine logs and try different Rocket.Chat configuration options.

For now where is no debug logging for message returned to Rocket.Chat, but if this advice doesn't help it could be added.

**Comment by brandonhinds** [comment]
Thanks for the write up @pru-mike.

I can see the "found jira keys" line in the debug logs, which is good, but still no posts in the channel. I have another integration setup with Gitlab which uses the same Bot account to post messages and it is fine, so I don't think it is a permissions issue.

Looking into it further it looks like this is a problem with my exact version of Rocket.Chat, as described [here](https://github.com/RocketChat/Rocket.Chat/issues/24374). I will try organise an upgrade in the next couple weeks and see if that resolves my issue. I'll close this issue for now, and let you know if I still have troubles.
